# +- - - - - - - - - - - - - - - - - -+
# | HiddenArmor - Configuration File  |
# +- - - - - - - - - - - - - - - - - -+

# Invisibility potion effect related section
invisibility-potion:
  # If players with the invisibility potion effect should always have their gear invisible as well.
  always-hide-gear: false

# Equipments to be ignored and not hidden section
ignore:
  # If leather armor should not be hidden and be shown even if the player is hiding his armor.
  # It is recommended to set this to true due to powder snow issues caused when the leather armor is hidden.
  leather-armor: true
  # Set this to true if you want to let your players show off their turtle helmet even when their armor is hidden.
  turtle-helmet: false
  # Set this to true if you want elytras to never be hidden.
  # If this is set to false, the elytra will only be hidden to other players due to minecraft limitations.
  elytra: false


# Set to true if you want the command to be allowed to all players by default or to false if you want
# the command to be allowed only to OPs and players with its permission.
default-permissions:
  # Command: /togglearmor
  # Description: Toggle the player's own armor visibility
  # Permission: hiddenarmor.toggle
  toggle: true
  # Command: /togglearmor <player>
  # Description: Toggle other player's armor visibility
  # Permission: hiddenarmor.toggle.other
  toggle-other: false

# Language related settings. Language files are located in the 'locale' folder inside de plugin folder.
locale:
  # By default, the plugin will use the client's language when sending them messages, but if there is no locale file
  # for its language, the plugin will use the default locale set in this option.
  default-locale: 'en-us'

# Used to inform when a new config update is available, don't change this
config-version: 2